### PR TITLE
Fixed : #24 added Javadocs for classes and functions of the library module

### LINKED ISSUE #24: [DOCUMENTATION] Write proper documentation for all library functions

### PR DESCRIPTION
**Pull request by dino-saurabh**
added Javadocs. which Closes #24 .

### CODE REVIEW

**Comment by dino-saurabh** [comment]
@krharsh17  I need help documenting BarGroup and one method in the Bar class!!.
please review my changes

File: library/src/main/java/in/krharsh17/barview/Bar.java [hunk 1]
```diff
@@ -13,10 +13,20 @@
 
 class Bar extends View {
 
+    /**
+     * It can be called by a anyone directly from code to create a new instance of the view.
+     * This constructor doesn’t have access to XML attributes, so you have to fill the parameters manually, using setters.
+     * @param context of the activity
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/Bar.java]:
```suggestion
    /**
     * It can be called by anyone directly from code to create a new instance of the view.
     * This constructor doesn’t have access to XML attributes, so you have to fill the parameters manually, using setters.
     * @param context of the activity
     */
```

File: library/src/main/java/in/krharsh17/barview/Bar.java [hunk 2]
```diff
@@ -38,6 +48,13 @@ protected void onAttachedToWindow() {
         this.setFocusable(true);
     }
 
+    /**
+     * ?
+     *
+     * @param view
+     * @param normalColor
+     * @param touchColor
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/Bar.java]:
```suggestion
    /**
     * Sets a ripple drawable as the background of the bar
     * The background can display ripples on touch
     * @param view - The view to set the background to
     * @param normalColor - Color when unpressed
     * @param touchColor - Color when pressed
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 3]
```diff
@@ -133,6 +163,9 @@ protected void onAttachedToWindow() {
 
     }
 
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Initializer function for the label segment
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 4]
```diff
@@ -154,6 +187,9 @@ void setupLabel() {
         this.addView(label);
     }
 
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Initializer function for the initial block
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 5]
```diff
@@ -177,6 +213,9 @@ else if (animationType == BarView.INTRO_ANIM_EXPAND){
 
     }
 
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Initializer function for the main bar
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 6]
```diff
@@ -190,6 +229,9 @@ public void setupBar() {
         bar.setProgress(progress,animationType,animationDuration);
     }
 
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Initializer function for the value tooltip
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 7]
```diff
@@ -210,6 +252,13 @@ void setupValue() {
         Bar.setRippleDrawable(value, Color.parseColor(color), Color.parseColor(rippleColor));
         this.addView(value);
     }
+
+    /**
+     * ?
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
     * Loads font from assets
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 8]
```diff
@@ -222,6 +271,10 @@ public static Typeface get(String name, Context context) {
         }
         return tf;
     }
+
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion

    /**
     * Sets constraints for all pieces of a BarGroup instance
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 9]
```diff
@@ -249,10 +302,21 @@ void applyConstraints() {
         constraintSet.applyTo(this);
     }
 
+    /**
+     * ?
+     * @param dp
+     * @return
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Converts density independent pixel units (dp) to pixel units (px)
     * @param dp
     * @return
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 10]
```diff
@@ -249,10 +302,21 @@ void applyConstraints() {
...
     int dp(float dp) {
         return Math.round(TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, dp, context.getResources().getDisplayMetrics()));
     }
 
+    /**
+     * ?
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
     * Animator function for the 'expand' intro animation
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 11]
```diff
@@ -273,6 +337,11 @@ public void onAnimationUpdate(ValueAnimator animation) {
         valueAnimator.start();
     }
 
+    /**
+     * ?
+     * @param labelText
+     * @return
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
    /**
     * Parses the label text to truncate or hyphenize the string to fit in the given space
     * @param labelText
     * @return
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 12]
```diff
@@ -295,6 +364,9 @@ else if (s.length() >= 8 && s.length() < 12) {
         return finalizedString.toString();
     }
 
+    /**
+     * ?
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]: @parthsharma07 Please provide the documentation for this

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 13]
```diff
@@ -325,6 +397,13 @@ public boolean willChangeBounds() {
             return true;
         }
     }
+
+    /**
+     * ?
+     *
+     * @param color
+     * @return
+     */
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]: @Alaska18 Please provide the documentation for this

File: library/src/main/java/in/krharsh17/barview/BarModel.java [hunk 14]
```diff
@@ -38,6 +46,16 @@ public void setFillRatio(Float fillRatio) {
...
 
+
+    /**
+     * parameterized constructor
+     *
+     *
+     * @param label for the barGroup instance
+     * @param value for approximating the length of Bargroup instance
+     * @param color hex color value for the fill of barGroup instance
+     * @param fillRatio --?
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarModel.java]:
```suggestion
     * @param fillRatio for determining the percentage of the bar to be filled
```

File: library/src/main/java/in/krharsh17/barview/BarView.java [hunk 15]
```diff
@@ -161,12 +175,23 @@ else if (animationType == BarView.INTRO_ANIM_EXPAND){
...
         }
     }
 
+    /**
+     * This method actuall instanciates BarGroups based on the BarModel passed in as
+     * a param and cumulates it into barGroups.
+     * @param data is a BarModel that contains all the required to
+     *             construct a BarGroup instance.
+     */
+
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarView.java]:
```suggestion
    /**
     * This method actually instantiates BarGroups based on the BarModel passed in as
     * a param and cumulates it into @param barGroups.
     * @param data is a BarModel that contains all the data required to
     *             construct a BarGroup instance.
     */

```

**Review by krharsh17 — CHANGES_REQUESTED** [review]

File: library/src/main/java/in/krharsh17/barview/BarView.java (hunk 15 above)
Comment (dino-saurabh) [reply library/src/main/java/in/krharsh17/barview/BarView.java]: @krharsh17 dont we use the @param notation only for the params passed to the function?

Comment (dino-saurabh) [reply library/src/main/java/in/krharsh17/barview/BarView.java]: I guess we use @link for it ? Not sure btw.

Comment (krharsh17) [reply library/src/main/java/in/krharsh17/barview/BarView.java]: Yeah, I think you're right. Just confirm it once though.

File: library/src/main/java/in/krharsh17/barview/BarGroup.java (hunk 12 above)
Comment (LuGO0) [reply library/src/main/java/in/krharsh17/barview/BarGroup.java]: please do reply @parthsharma07 :)

File: library/src/main/java/in/krharsh17/barview/BarGroup.java (hunk 13 above)
Comment (LuGO0) [reply library/src/main/java/in/krharsh17/barview/BarGroup.java]: Please do reply @Alaska18

**Comment by dino-saurabh** [comment]
@krharsh17  I really had a hard time fixing up merge conflicts please review and suggest changes before some conflicts arise again :))

**Comment by krharsh17** [comment]
Actually I am waiting for @parthsharma07 and @Alaska18 to put in their pieces of documentation. Your work is perfect. Once they put in their parts, I'll approve and merge this.

File: library/src/main/java/in/krharsh17/barview/BarGroup.java (hunk 13 above)
Comment (Alaska18) [reply library/src/main/java/in/krharsh17/barview/BarGroup.java]: This creates a gradient drawable background for the bars - sets a shape, a color and radius for the corners.
@param color is the color in int which is  used as the background color.

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 16]
```diff
@@ -487,6 +560,13 @@ public boolean willChangeBounds() {
...
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion

    /**
     * This creates a gradient drawable background for the bars - sets a shape, a color and radius for the corners.
     * @param color is the color in int which is used as the background color.
     */
```

File: library/src/main/java/in/krharsh17/barview/BarGroup.java [hunk 17]
```diff
@@ -457,6 +527,9 @@ else if (s.length() >= 8 && s.length() < 12) {
         return finalizedString.toString();
     }
 
+    /**
+     * ?
```
Comment (parthsharma07) [inline library/src/main/java/in/krharsh17/barview/BarGroup.java]:
```suggestion
     * The animation function takes the actual view-group, animation duration and target width in dp as it's arguments
     and takes initial width as 0 dp. After this, using ValueAnimator, the barview is made to expand to provided width
     in the specified time duration and it's visibility is set to visible during animation.
```

**Comment by krharsh17** [comment]
@LuGO0 The comments are here now. You can merge them, update your base branch and squash all your commits into one so that I may merge it.

**Comment by dino-saurabh** [comment]
sure I would do that @krharsh17

File: library/src/main/java/in/krharsh17/barview/Constants.java [hunk 18]
```diff
@@ -1,7 +1,6 @@
 package in.krharsh17.barview;
 
 public interface Constants {
-
```
Comment (krharsh17) [inline library/src/main/java/in/krharsh17/barview/Constants.java:4]: This change wasn't needed. However, I'll not delay this PR any more. But please take care from the next time.

**Review by krharsh17 — APPROVED** [review]

File: library/src/main/java/in/krharsh17/barview/Constants.java (hunk 18 above)
Comment (dino-saurabh) [reply library/src/main/java/in/krharsh17/barview/Constants.java:4]: Ill do that @krharsh17
